import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '../components/navbar/Navbar'
import Provider from '../ui/provider'
import { SWRProvider } from '../swr-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Provider>
            <Navbar />
            <main>
              {children}
            </main>
          </Provider>
      </body>
    </html>
  )
}